<?php

return [

    'plans' => [
        'start' => [
            'label' => 'Старт',
            'features' => [
                'leads',
                'orders',
                'contractors',
                'tasks',
                'grid_views',
            ],
            'limits' => [
                'users' => 5,
                'orders_per_month' => 200,
                'storage_mb' => 2048,
            ],
        ],
        'pro' => [
            'label' => 'Про',
            'features' => [
                'leads',
                'orders',
                'contractors',
                'tasks',
                'grid_views',
                'documents',
                'payment_schedules',
                'print',
                'mail',
                'sales_scripts',
                'sales_book',
                'sales_trainer',
                'proposals_html',
                'how_much_fits',
                'mcp_read',
                'traklo_mobile',
            ],
            'limits' => [
                'users' => 25,
                'orders_per_month' => 2000,
                'storage_mb' => 20480,
            ],
        ],
        'enterprise' => [
            'label' => 'Корпоративный',
            'features' => [
                'leads',
                'orders',
                'contractors',
                'tasks',
                'grid_views',
                'documents',
                'payment_schedules',
                'print',
                'mail',
                'sales_scripts',
                'sales_book',
                'sales_trainer',
                'proposals_html',
                'how_much_fits',
                'mcp_read',
                'mcp_write',
                'fleet',
                'disposition',
                'management_accounting',
                'budgeting',
                'company_planning',
                'ai_analytics',
                'load_board',
                'import_cost',
                'integrations',
                'custom_domain',
                'traklo_mobile',
            ],
            'limits' => [
                'users' => null,
                'orders_per_month' => null,
                'storage_mb' => null,
            ],
        ],
    ],

];
